name: liv_app
description: "Application de livraison"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.1
  intl: ^0.19.0
  fl_chart: ^0.65.0
  url_launcher: ^6.3.1
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icons8-livraison-réussie-50 (1).png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icons8-livraison-réussie-50 (1).png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/icons8-livraison-réussie-50 (1).png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icons/icons8-livraison-réussie-50 (1).png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/icons8-livraison-réussie-50 (1).png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
